In [2]:
# Question 2 (a) - compute the weight vector w = [w0,w1,w2]T for linear regression
# h(x) = sum(wixi) = wTx ≈ y
# w = (XTX)−1XTy ------ minimize error

import numpy as np
import sklearn

Xt = np.matrix("1,1,1,1;3,2,1,-1;2,2,-1,-3") # 4x3 transpose of X
X = Xt.transpose() #3x4 given
y = np.matrix("3;1;-1;-3") #1x1 given

from numpy.linalg import inv

# dot_XtX = inv(X*Xt)  # 4x3 times 3x4
# print(dot_X) # 4x4 

#dot_XY = Xt*y # 3x4 times 4x1
# print(dot_XY) # 3x1

w = inv(Xt*X)*Xt*y
w # weight vector - lm ME

matrix([[-1.66666667],
        [ 1.33333333],
        [ 0.11111111]])

In [3]:
# Question 2 (b) - find w for linear regression using sklearn
from sklearn.linear_model import LinearRegression

X = np.array(X) #3x4
y = np.array(y) #4x1

reg = LinearRegression().fit(X, y)

print(reg.coef_) # w?

print(reg.score(X, y))
print(reg.intercept_) #w


[[0.         1.33333333 0.11111111]]
0.9666666666666667
[-1.66666667]


In [4]:
# Question 3 - Fisher's linear discriminant analysis (LDA)
# minimize the “within-class covariance”

X1 = np.array([[4],[3]])
X2 = np.array([[2],[2]])
X3 = np.array([[1],[1]])
X4 = np.array([[-2],[1]])

# y = np.array([[1],[1],[-1],[-1]]) 
#print(y)

# Calculate the mean vectors per class
m1 = (X1+X2)/2
m2 = (X3+X4)/2
print(m1) #2x1
print(m2) #2x1
print('\n')

# Calculate the scatter matrices for the SW (Scatter within) and sum the elements up
Sw = ((X1 - m1) * ((X1 - m1).transpose())) + ((X2 - m1) * ((X2 - m1).transpose())) + ((X3 - m2) * ((X3 - m2).transpose()) + ((X4 - m2) * ((X4 - m2).transpose())))
print(Sw)
print('\n')

from numpy.linalg import inv
W = inv(Sw)*(m2-m1) # optimal solution 
print(W) # vector w=[w1,w2]


[[3. ]
 [2.5]]
[[-0.5]
 [ 1. ]]


[[6.5 1. ]
 [1.  0.5]]


[[-0.77777778  1.55555556]
 [ 0.66666667 -4.33333333]]


In [8]:
# Question 4 - heart disease dataset
import pandas as pd
df = pd.read_csv('heart_disease_data.txt')
df.head(5)
#df.shape #100x14

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    1  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

In [63]:
import pandas as pd
import numpy as np
import sklearn.discriminant_analysis as sda 
import sklearn.linear_model as lm
# lda
df = pd.read_csv('heart_disease_data.txt') 
data = df.to_numpy()
x = data[:,0:13]
y = data[:,-1] #num

# import random
# random.seed(120)

perceptron = lm.Perceptron(max_iter=500) 

perceptron.fit(x,y)
print(perceptron.coef_)
perceptron.intercept_


[[  731.     67.    197.    325.     23.    -10.    116.  -1187.     59.
    189.9    93.    159.    508. ]]


array([6.])

In [69]:
# weight vector w for linear discriminant analysis (LDA)
import sklearn.linear_model as lm

lda = sda.LinearDiscriminantAnalysis() 
lda.fit(x,y)
lda.coef_

print(lda.coef_)
lda.intercept_


[[-0.00473584  1.26780721  1.30117132 -0.03437771  0.01697281 -0.07954438
   0.66800376 -0.01986038  0.32713953  0.78643444  0.25465599  1.02247583
   0.99167057]]


array([-9.59068692])